# name for this workflow
name: Deploy Frontend to Azure Static Web App

# trigger(s) for this workflow - how should it be initiated?
on:
  push:
    branches: [ main ]
    paths: 
      - 'src/frontend/**'
  workflow_dispatch:  # Allow manual triggering

# environment variables used in this workflow
env:
  NODE_VERSION: '20.x'
  APP_LOCATION: 'src/frontend'  # Root location of app source code
  OUTPUT_LOCATION: 'dist'       # Location of build output relative to app location

# jobs that will run in this workflow
jobs:
  # job name
  build-and-deploy:
    # runs on the latest Ubuntu (Linux) environment
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    # steps that will be executed for the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        lfs: false
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'
        
    - name: Configure npm authentication
      run: |
        # Add authentication to the existing .npmrc file in the frontend directory
        cd ${{ env.APP_LOCATION }}
        
        # Create base64 encoded auth token for JFrog Artifactory
        AUTH_TOKEN=$(echo -n "${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }}" | base64 -w 0)
        echo "//carmax.jfrog.io/artifactory/api/npm/npm/:_auth=${AUTH_TOKEN}" >> .npmrc
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ env.APP_LOCATION }}
      
    - name: Build application
      run: npm run build:dev
      working-directory: ${{ env.APP_LOCATION }}
      env:
        # Add any environment variables needed for build here
        NODE_ENV: production
        
    - name: Deploy to Azure Static Web App
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        # REQUIRED: Set this in GitHub repository secrets
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        
        # Repository configuration
        repo_token: ${{ secrets.GITHUB_TOKEN }}  # Used for GitHub integrations (auto-generated)
        action: "upload"
        
        # Application configuration
        app_location: ${{ env.APP_LOCATION }}      # App source code path
        output_location: ${{ env.OUTPUT_LOCATION }} # Built app content directory
        app_build_command: 'npm run build:dev'     # Override default build command
        
        # Optional: API configuration (uncomment if you have Azure Functions API)
        # api_location: "src/api"  # Api source code path - optional
        
        # Skip API build if no API exists
        skip_api_build: true